- name: Testing the copy module against a targeted host
  hosts: {{ hosts }}
  gather_facts: false
  become: true

  tasks:
    - name: Copy files to dest directory
      copy:
        remote_src: true
        src: /home/ec2-user/
        dest: /tmp/
        mode: 0755
        owner: root
        group: root
