- name: Testing the copy module against a targeted host
  hosts: node3
  gather_facts: false
  become: true

  tasks:
    - name: Copy files to dest directory
      copy:
        remote_src: true
        src: /home/ec2-user
        dest: /usr/bin/
        directory_mode: '0777'
        owner: root
        group: root

#     - name: Update file permissions
#       file:
#         path: /tmp/hello.txt
#         mode: 0777
