---
- name: Install MongoDB
  hosts: database 
  gather_facts: false 
  become: true

  tasks: 
  - name: Install package mongodb-org
    ansible.builtin.package:
      name: mongodb-org
      state: present
      




