---
- name: Test URI module
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Getting Inventory Data using Controller API with API token
    ansible.builtin.uri:
      url: https:/
      method: GET
      body_format: json
      return_content: yes
      headers:
        Authorization: "Bearer """
      validate_certs: no
    register: results
  
  - name: Print results
    ansible.builtin.debug:
      var: results
