---
- name: Test URI module
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Getting Inventory Data using Controller API with API token
    ansible.builtin.uri:
      url: https://my-automation-controller-aap.apps.ocp4.tigerlab.io/api/v2/inventories
      method: GET
      body_format: json
      return_content: yes
      headers:
        Authorization: "Bearer GjDkeGezGuIzeOjr9vj1pkAA24Bkn5"
      validate_certs: no
    register: results
  
  - name: Print results
    ansible.builtin.debug:
      var: results
