---
- name: Test URI module
  hosts: localhost
  gather_facts: false


  tasks:
  - name: Getting Inventory Data using Controller API with API token
    ansible.builtin.uri:
      url: https://my-automation-controller-aap.apps.ocp4.tigerlab.io/api/v2/inventories
      method: GET
      body_format: json
      headers:
        Authorization: "Bearer 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"
      validate_certs: no
    register: results
      
