---
- name: test file copy
  hosts: rhel7
  gather_facts: false
  become: true

  tasks:
    - name: do the copy of files
      ansible.builtin.copy:
        remote_src: true
        src: /tmp/filesrc/
        dest: /tmp/filedest/
        mode: '0777'
        owner: root
        group: root
