---
- name: test file copy
  hosts: rhel7
  gather_facts: false
  become: true

  tasks:
    - name: copy file
      ansible.builtin.copy:
        src: /tmp/filesrc/
        dest: /tmp/filedest/
        owner: root
        group: root
